language: node_js
node_js:
  - 5.0
  - 5.1
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 5.7
  - 5.8
  - 5.9
  - 5.10
  - 5.11
env:
  - TRAVIS=true
os:
  - linux
services:
  - couchdb
sudo: false
before_install: npm install -g justo-cli
install: npm install
before_script:
  - curl -X PUT localhost:5984/test-plugin
#script:
#after_success:
#after_failure:
#after_script:
